import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Space_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-black">
      <body className={`${geistSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
